require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'app/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 40
  ExcludedMethods: ['describe', 'context', 'it']

Metrics/AbcSize:
  Enabled: false

Lint/Debugger:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*_spec.rb

RSpec/MessageChain:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false
